leeanneahammond/project_three

asisme_app/package-lock.json
asisme_app/package.json
asisme_app/src/App.js

added basic react-router

---

asisme_app/src/App.js
asisme_app/src/components/NavBar.js

NavBar component created in components folder and added to app.js

added NavBar component with routes

---

asisme_app/src/components/States.js

added list of states

---

asisme_app/src/components/Api.js
asisme_app/src/components/States.js

started api

---

asisme_app/src/App.js
asisme_app/src/components/NavBar.js

moved route path

---

asisme_app/src/components/States.js

updated states

---

asisme_app/src/App.js
asisme_app/src/components/Form.js
asisme_app/src/components/Map.js
asisme_app/src/components/NavBar.js
asisme_app/src/components/State.js

added form to state.js

---

asisme_app/src/components/State.js

testing something out

---

asisme_app/src/App.css
asisme_app/src/components/StateList.js

updated stateslist.js

---

asisme_app/src/App.js
asisme_app/src/components/StateMap.js

added react-map

---

asisme_app/src/App.js
asisme_app/src/components/StateMap.js

linked react map

---

asisme_app/src/App.css

updated css

---

asisme_app/src/components/StateMap.js

fixed back link to homepage

---

asisme_app/src/components/State.js

added update functionality to support button

added update functionality to support button

---

asisme_app/src/App.css
asisme_app/src/components/Form.js

updated css again

---

asisme_app/public/index.html
asisme_app/src/App.css
asisme_app/src/components/StateList.js

added fonts

---

asisme_app/src/App.css
asisme_app/src/components/State.js

fixed background styling

---

asisme_app/src/App.css
asisme_app/src/components/State.js

updated support button cursor to pointer on hover

updated support button cursor to pointer on hover

---

asisme_app/src/App.css
asisme_app/src/components/Form.js
asisme_app/src/components/NavBar.js
asisme_app/src/components/State.js

added more css and up[dated form.js

---

asisme_app/src/components/StateMap.js

added heat map colors

---

asisme_app/src/App.css
asisme_app/src/components/MapKey.js

added more to key

---

asisme_app/src/App.css
asisme_app/src/components/MapKey.js

fixed responsive design
